### ISSUE TITLE
Would it be possible to have an option to add labels on the PR?

### ISSUE THREAD

**Issue by rlejeune** [taichi/actions-package-update#14]
For example:

```
steps:
  - uses: ybiquitous/npm-audit-fix-action@v1
    with:
      labels: [dependencies, security]
```
