### ISSUE TITLE
GitHub ignores GITHUB_WORKSPACE env variable

### ISSUE THREAD

**Issue by nikrolls** [taichi/actions-package-update#9]
No matter how you set this variable in a GitHub action, it's ignored (or possibly overwritten by GitHub). This means you can't run `actions-package-update` in any folder other than the root. 

You can verify this by creating a workflow step:
```yaml
- name: Attempt to set GITHUB_WORKSPACE
  env:
    FOO: bar
    GITHUB_WORKSPACE: ./foo
  run: printenv
```
Observe that the output shows that the `GITHUB_WORKSPACE` variable has not been changed:
```
Run printenv
  printenv
  shell: /bin/bash -e {0}
  env:
    FOO: bar
    GITHUB_WORKSPACE: ./foo
# ...
FOO=bar
# ...
GITHUB_WORKSPACE=/home/runner/work/actions-package-update/actions-package-update
```
This is also the case if you use `set-env`, because all that does is create an `env` property for future steps as if you had put them into the workflow yourself.

To solve this you would need to create a different environment variable that we can use which GitHub will not ignore or clobber (`WORKING_DIRECTORY` maybe?).
